package httpprefix

import (
	"net/url"
	"strings"
)

// RouteURL generates an external URL reference for a prefix-free application path.
// The prefix is normalized with NormalizeRoutePrefix; callers needing strict
// configuration should first use ValidateRoutePrefix.
//
// Local absolute paths gain the prefix, preserving their escaping, query, and
// fragment. For example, RouteURL("/app", "/pages/foo?q=bar#top") returns
// "/app/pages/foo?q=bar#top". RouteURL("/app", "/") returns "/app/".
//
// Pass application-local paths, not URLs already generated by this function.
// No attempt is made to recognize an already-prefixed path: RouteURL("/pages",
// "/pages/foo") returns "/pages/pages/foo".
//
// Malformed local paths, network-path references ("//host"), backslashes,
// line breaks, and dot segments fall back to the deployment root. Escaped path
// characters are checked after decoding as well. External URLs and relative
// references are returned unchanged. This function is not a general URL
// sanitizer or an authorization check for redirect destinations.
func RouteURL(prefix, target string) string {
	if !isAbsolutePathReference(target) {
		return target
	}

	prefix = NormalizeRoutePrefix(prefix)
	root := prefix + "/"

	u, err := url.Parse(target)
	if err != nil {
		return root
	}
	if isUnsafeLocalReference(target, u.Path) {
		return root
	}

	return prefix + target
}

// isAbsolutePathReference reports whether target starts with an absolute path marker.
func isAbsolutePathReference(target string) bool {
	return strings.HasPrefix(target, "/")
}

// isUnsafeLocalReference reports whether a local URL reference can escape or alter routing semantics.
func isUnsafeLocalReference(rawTarget, decodedPath string) bool {
	return isUnsafePath(rawTarget) || isUnsafePath(decodedPath) || hasDotSegment(decodedPath)
}

// isUnsafePath reports whether path is network-path-like or contains unsafe control/path characters.
func isUnsafePath(path string) bool {
	return strings.HasPrefix(path, "//") || strings.ContainsAny(path, "\\\r\n")
}

// hasDotSegment reports whether path contains a literal or decoded "." or ".." segment.
func hasDotSegment(path string) bool {
	for _, segment := range strings.Split(path, "/") {
		if isDotSegment(segment) {
			return true
		}
	}
	return false
}

// isDotSegment reports whether segment is the current or parent directory marker.
func isDotSegment(segment string) bool {
	return segment == "." || segment == ".."
}
