package httpprefix

import (
	"net/url"
	"strings"
)

// RouteURL generates an external URL reference for a prefix-free application path.
// The prefix is normalized with NormalizeRoutePrefix; callers needing strict
// configuration should first use ValidateRoutePrefix.
//
// Local absolute paths gain the prefix, preserving their escaping, query, and
// fragment. For example, RouteURL("/app", "/pages/foo?q=bar#top") returns
// "/app/pages/foo?q=bar#top". RouteURL("/app", "/") returns "/app/".
//
// Pass application-local paths, not URLs already generated by this function.
// No attempt is made to recognize an already-prefixed path: RouteURL("/pages",
// "/pages/foo") returns "/pages/pages/foo".
//
// Malformed local paths, network-path references ("//host"), backslashes,
// line breaks, and dot segments fall back to the deployment root. Escaped path
// characters are checked after decoding as well. External URLs and relative
// references are returned unchanged. This function is not a general URL
// sanitizer or an authorization check for redirect destinations.
func RouteURL(prefix, target string) string {
	if !strings.HasPrefix(target, "/") {
		return target
	}
	prefix = NormalizeRoutePrefix(prefix)
	root := prefix + "/"
	u, err := url.Parse(target)
	if err != nil || strings.HasPrefix(target, "//") || strings.ContainsAny(target, "\\\r\n") {
		return root
	}
	if strings.ContainsAny(u.Path, "\\\r\n") || strings.HasPrefix(u.Path, "//") {
		return root
	}
	for _, segment := range strings.Split(u.Path, "/") {
		if segment == "." || segment == ".." {
			return root
		}
	}
	return prefix + target
}
